### ISSUE TITLE
Update to Flyway 6.5.7

### ISSUE THREAD

**Issue by dwpramik** [sbt/flyway-sbt#72]
There is currently an open pull request to [update to Flyway 6.5.5](https://github.com/flyway/flyway-sbt/pull/71). However, [Flyway 6.5.7](https://flywaydb.org/documentation/releaseNotes#6.5.7) was just released yesterday that updates the Postgres driver version due to a known XXE vulnerability.

Instead of going to 6.5.5 it would be beneficial to just make the jump to 6.5.7 to ensure that the vulnerability is handled.

**Comment by sullis** [comment]
https://github.com/flyway/flyway-sbt/pull/73

**Comment by mkurz** [comment]
Things will go forward soon:
- #93

**Comment by eed3si9n** [comment]
Closing since 7.4.0 has been out - https://repo1.maven.org/maven2/io/github/davidmweber/flyway-sbt_2.12_1.0/7.4.0/
