### ISSUE TITLE
Update to latest Flyway version (9.22.0)

### ISSUE THREAD

**Issue by dkichler** [sbt/flyway-sbt#90]
This plugin is ~2.5 years out of date with the current version of Flway.  It's probably due for an upgrade.

**Comment by mkurz** [comment]
We are moving forward soon, see
- #93

**Comment by john-joe-givery** [comment]
@mkurz Any update on this move?

**Comment by mkurz** [comment]
@john-joe-givery It's going to happen soon.

**Comment by eed3si9n** [comment]
https://github.com/sbt/flyway-sbt/releases/tag/v9.22.0 is out

**Comment by mkurz** [comment]
Help is needed to upgrade to latest Flyway 10.21.0:
- #108
